### ISSUE TITLE
Unable to click buttons

### ISSUE THREAD

**Issue by Jumes-1** [Dimitar5555/WaterCompany#14]
http://prntscr.com/fl0q8x

Unable to click buttons on the right hand side of the screen, it seems like the notifications div is overlapping the button, which means I cannot click the button.

**Comment by Jumes-1** [comment]
#15 

Could be a possible fix for it.

**Comment by Dimitar5555** [comment]
Could, but it isn't. That thing is in `<body>` and will auto move depending on the width.
