### ISSUE TITLE
Bank return doesn't work

### ISSUE THREAD

**Issue by Doony88** [Dimitar5555/WaterCompany#18]
Hi there,
i packed a whole lot of money into the bank to get some interest on it. But if i want to get the money back and press "return max" nothing happens. When i insert any amount of money and hit return it says the bank file is empty. 

greets DOony
![bankaccount](https://user-images.githubusercontent.com/35724193/35266653-2fa49b14-0024-11e8-8283-00cd263bd0f6.JPG)
![bankaccount-2](https://user-images.githubusercontent.com/35724193/35266654-2fc1d1fc-0024-11e8-84cf-8958b1581e04.JPG)
![bankaccount-popup](https://user-images.githubusercontent.com/35724193/35266656-2fe499ee-0024-11e8-9926-d8234372b4ce.JPG)

**Comment by Dimitar5555** [comment]
Return is for loan. You should use withdraw instead.

**Comment by DatrixTHLK** [comment]
That works for me. Thanks!
