### ISSUE TITLE
"Homes" upgrade tab can only be opened once [0.4 recode]

### ISSUE THREAD

**Issue by jodylecompte** [Dimitar5555/WaterCompany#20]
**Describe the bug**
When navigating to the "Homes" section of the upgrades area, it loads successfully the first time but requires a browser refresh to open a second time.

**To Reproduce**
1. Go to upgrades and click "Homes"
2. Click any other area of upgrades
3. Attempt to click back home, this should not work
4. Refresh Browser
5. Starting at 1 should work again.

**Expected behavior**
Tabs be navigable in any other and able to be opened multiple times.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 18.04
 - Browser: Google Chrome
 - Version: Version 71.0.3578.80 (Official Build) (64-bit)

**Comment by jodylecompte** [comment]
Upon playing with this further, I also discovered that by clicking into "Bank" and then into "Home" you could re-access without a page-reload, so it seems to be something about the switch to one of the sub categories of upgrades.

**Comment by Dimitar5555** [comment]
I was able to reproduce the bug. I will look into it.

**Comment by Dimitar5555** [comment]
#23

**Comment by Dimitar5555** [comment]
This bug should be fixed now.
#23

**Comment by jodylecompte** [comment]
@Dimitar5555 Verified fix is working in production for me. 

Great work! I had a lot of fun playing and the new changes you pushed out with this fix look great too.
