### ISSUE TITLE
NaN pipes

### ISSUE THREAD

**Issue by mlonghi-git** [Dimitar5555/WaterCompany#24]
**Describe the bug**
Bugged number of pipes

"Not enough money to buy NaN pipes"

**To Reproduce**
Just normally playing, auto buy was set

**Expected behavior**
Number of buyable pipes
**Screenshots**
https://prnt.sc/tpsye5

**Desktop (please complete the following information):**
 - OS: windows 10 pro
 - Browser: chrome 84.0.4147.89
 - Version version 0.3.4.1 Beta

**Comment by Dimitar5555** [comment]
Can you open the console by pressing F12, write 
```
console.log(localStorage.save)
```
and paste the response here?
