### ISSUE TITLE
Huge Bug

### ISSUE THREAD

**Issue by Abanator101** [Dimitar5555/WaterCompany#25]
Hi my name is Abe, I love your game but I found a bug.So I went to get a loan for $5,000 and I accidentally didnt remove the zero from the line and so it said, $05000.I pressed get and it kept spamming me with this 
![Screenshot 2020-10-14 at 2 38 21 PM](https://user-images.githubusercontent.com/72415282/96037071-f4002e80-0e2a-11eb-9d9e-627ac65a36fd.png)I went to return max expecting i got 5k but i got no money and it wouldn't let me return anything, also it kept spamming that i didnt have enough money to pay loan so it kept raising the amount I owed, now its at like 60k.(keep in mind how much money I have)
![Screenshot 2020-10-14 at 2 41 05 PM](https://user-images.githubusercontent.com/72415282/96037370-5d803d00-0e2b-11eb-85f8-da7559bec669.png) Now it won't let me invest in my bank account and wont stop spamming "not enough money"
Plz Fix

**Comment by Dimitar5555** [comment]
The bug should be fixed now. If the issue persist try to force refresh the game(Ctrl+F5). If that doesn't happen you can reopen this issue.
