### ISSUE TITLE
Bank Loan Upgrade - Not increasing maximum loan [0.4 recode]

### ISSUE THREAD

**Issue by switchlove** [Dimitar5555/WaterCompany#26]
**Describe the bug**
When purchasing the Bank's maximum loan amount upgrades, the maximum load amount does not increase.

**To Reproduce**
1. Go to 'Upgrades'
2. Purchase a level or two of 'Increase maximum loan by 100%'

**Expected behavior**
Under the upgrade text, the 'Maximum loan $100.00K->$200.00K' should change to reflect the updated maximum loan amount. 
Also under the Bank tab, the 'Max loan' amount should increase as well. 

**Screenshots**
![ss-one](https://i.imgur.com/eV8NtRN.png)
![ss-two](https://i.imgur.com/eWV6l6B.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro Build 20H2
 - Browser: Google Chrome
 - Version: 86.0.4240.198 (Official Build) (64-bit)

**Comment by Dimitar5555** [comment]
Thanks for reporting this bug. It has been fixed. If you happen to find any other bugs, feel free to open a new issue report.
