### ISSUE TITLE
Is this game still active?

### ISSUE THREAD

**Issue by Owenm05** [Dimitar5555/WaterCompany#28]
I’m just wondering if this game is still updated or if it has been abandoned?

**Comment by Dimitar5555** [comment]
It's abandoned for the time being. I have some plans for it but I'm working on other projects currently.

**Comment by Owenm05** [comment]
Is there supposed to be a about page? when I click it it show nothing

**Comment by Dimitar5555** [comment]
It's a leftover from the previous version. I've removed it and it should be gone on the live version soon.

**Comment by Owenm05** [comment]
One more thing I want to say is I’m a really big fan of your water company
