### ISSUE TITLE
Minor typos

### ISSUE THREAD

**Issue by boisei0** [Dimitar5555/WaterCompany#4]
- When starting a new game, a popup is shown mentioning the game is experimental, and that "Some features can not work properly and it could **brake** your game!". While the words sound the same, the correct word would be 'break' in this sentence.
https://github.com/Dimitar5555/WaterCompany/blob/96f439681079f9ecd9dc7503ba38900ddcd57aec/js/script.js#L159
- The FAQ has a question "I want **ot** get x money via loan but I can't. Why?"
https://github.com/Dimitar5555/WaterCompany/blob/96f439681079f9ecd9dc7503ba38900ddcd57aec/index.html#L496

**Comment by Dimitar5555** [comment]
Thanks, it's fixed. Sometimes when people type, they can make some mistakes without noticing :) I will leave the issue open if you or someone else finds a new typo.
